version: '2'

x-base: &base
  build: .
  image: slack-archiver
  environment: 
    - NODE_ENV=production
    - MONGO_URL=mongodb://mongo:27017
    - SLACK_API_TOKEN=xoxp-
    #- SLACK_BOT_TOKEN=xoxb-
  links:
    - mongo
  depends_on:
    - mongo

services:
  web:
    <<: *base
    restart: always
    ports:
      - 3000:3000
    command: npm run web
    restart: always
  import:
    <<: *base
    volumes:
      - /your_zip:/import.zip
    command: npm run import /import.zip
  mongo:
    image: mongo:4.1.5
    restart: always
